### PR TITLE
Date Window API

### PR DESCRIPTION
**Pull request by jesseditson**
Add a "DateWindow" API allowing external control and visibility of the currently presented date windows.

## Description

Adds 2 new props to both kinds of calendars:

- initialMonth: used for starting the visible calendar at a specific date rather than whatever the current month is
- onUpdateWindow: a callback that is called whenever the visible date range changes (including on initialization)

These APIs together allow the consumer to track the current window so they can query an external data source based on what the user is looking at rather than having to fetch data for all time.

## Motivation and Context

In an application I was building, I have an external data source that controls things like disabled days and selected days. Rather than having the calendar have to fetch data for all time, I wanted to just fetch the range that the user was looking at, so I needed the ability to set a custom start month and to be notified any time the user changes which months they are looking at.

## How Has This Been Tested?

I've added stories to both kinds of calendars and manually tested that the return values from onUpdateWindow match my expectations. This can also be seen in the below video:

## Screenshots:

https://user-images.githubusercontent.com/370239/112769112-38941680-8fd4-11eb-99c4-eb7997e922c2.mp4

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by samsam-ahmadi** [comment]
@jesseditson, Yaaay,  Apologies for the delayed response– work stuff and time zone problem 

We had this before in the first version. We received the sorted list of days and pick up the first item and give it to the calendar to update the month and `Year`. 

https://github.com/samsam-ahmadi/react-trip-date/blob/80d7b1218c216af42b041aea387c14129e50c792/src/calendar/date-picker.tsx#L34

These days I was looking to find a better solution for that. We can handle it with props. Also, we can take it in the inner components like that we had before. 

If we want to handle it with the props, we need to pass date to it and handle the year for the calendar too, for example, the user puts the 1993-02-10

For the name of props, we can change it to something that includes the year, for example: 
initialCalendarView, initialMonthAndYear

Also for `onUpdateWindow` we can have something like: 
onRangeDateInScreen ,onRangeDateView  

So what you think about that?

**Comment by jesseditson** [comment]
No hurry on responses! You're already one of the fastest OSS responders I've seen. I'll be much slower!

The changes sound great to me. I'll update this PR to reflect them. Just to clarify, is `onRangeDateInScreen` just a name change with the same type? I'll assume it is, and the changes I'll plan on making are:

- Swap out `initialMonth` for `initialMonthAndYear` so the year can also be defaulted
- Rename `onUpdateWindow` to `onRangeDateInScreen`

**Comment by samsam-ahmadi** [comment]
@jesseditson  Thanks, Yeah I agree with the changes  ✌️

**Comment by jesseditson** [comment]
Ok, updated the API as we discussed! Let me know if anything else stands out!

**Comment by samsam-ahmadi** [comment]
@jesseditson   Thank you very much. That would be great.  I checked the codes and everything perfect.

I thought if we want to use this calendar for a birthday's calendar(it's a simple example), we need to extract year and month from this string "1993-02-04" from the server and put it to `initialMonthAndYear:{{year, month}}` so I thought we can make it simpler 

So what do you think if we make the `initialMonthAndYear` to `string` and take the date string from it, for example: 
initialMonthAndYear="1993", initialMonthAndYear="1993-11" or initialMonthAndYear="1993-11-25" to set month and year directly inside of component 

and put it to the dayjsLocalized like this: dayjsLocalized(jalali,initialMonthAndYear)

In this case, we can also automatically change the calendar if we don't have the initialMonthAndYear, 
and if we have selectedDays for date picker we can sort them and get the first item and put it into dayjsLocalized(jalali,firstItemOfSelectedDaysOfDatePicker)

Or for range pickers, we can get selectedDays.from  and put it into dayjsLocalized(jalali,selectedDays.from)


What do you think about these changes? 
- make the initialMonthAndYear string.
- if we haven't the initialMonthAndYear props, and if we have the selectedDays, we can set the calendar automatically by selectedDays values.

**Comment by jesseditson** [comment]
Ah yeah that API sounds more consistent to me, I'll make the changes!

**Comment by samsam-ahmadi** [comment]
@jesseditson, Hi, I was thinking you are busy so I changed the codes, Would you please check this change and if we need more change to tell me. 

Thanks.

**Comment by jesseditson** [comment]
Oh man that's amazing! I'll test it out now!

**Comment by jesseditson** [comment]
Ok, updated some minor stuff - used an `else if` instead of an `&&` inside an `else`, and used a non-default date in the stories so the functionality is better demonstrated. One side effect of the code is that if you have a selected date, you can't change the date range using this API. That seems intentional, but wanted to make sure it was! Otherwise I think this one is ready to go!

**Comment by samsam-ahmadi** [comment]
Ahhh, Yeah you are right, so what are you thinking about these changes? 

```js  
useEffect(() => {
    // Add initialMonthAndYear to first condition to make sure  initialMonthAndYear is first priority
    if (!initialMonthAndYear && selectedDays?.from) {
      setSource(dayjsLocalized(jalali, selectedDays?.from));
    } else if (initialMonthAndYear) {
      setSource(dayjsLocalized(jalali, initialMonthAndYear));
    }
    // we remove selectedDays and jalali dependency to just run if we have any changes for initialMonthAndYear
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ initialMonthAndYear]);
```

**Comment by jesseditson** [comment]
That seems like it would work! I don't have a personal opinion, both behaviors seem reasonable based on the prop name!

**Comment by samsam-ahmadi** [comment]
@jesseditson , sorry if I bother you, I did some changes, 
I make option two for our code, if developers put the value to selected days from the server, if every time this prop change, the useEffect for initialMonthAndYear will be called again, so I was thinking if the user is in the 2020 year and server sends the first item of selectedDays 2019 again. so the calendar going to the 2019 year so it's not good for the user experience. 
so I removed selectedDays from the dependency  😁

**Comment by jesseditson** [comment]
Amazing, thanks so much for getting this over the line!

**Comment by samsam-ahmadi** [comment]
@jesseditson, Thank you for your amazing work ❤️

**Pull request merged**
